export const INCREMENT = "INCREMENT";
export const MULTIPLY = "MULTIPLY";
export const INP_TEXT = "INP_TEXT";
export const COMENT_CREATE = "COMENT_CREATE";
export const COMENT_UPDATE = "COMENT_UPDATE";
export const COMENT_DELETE = "COMENT_DELETE";

export const COMMENTS_LOAD = "COMMENTS_LOAD";
export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";

export const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON";
export const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF";
